version: '3'
services:
  backend:
    build:
      context: ./
    command: rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./shop_frontend2
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3000  # Замените на правильный API URL
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
